trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

  - checkout: self

  - script: |
      git remote add github https://github.com/FangChenYi/ocard-server.git
      git fetch github
      git checkout main
      git pull github main
      git remote add azure https://dev.azure.com/fx1github/_git/test
      git push azure main --force
    displayName: 'Sync GitHub to Azure DevOps Repos'
