trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  sonar.projectKey: 'test_test_8a1c51d7-e32e-41af-8167-446a1aada390'
  sonar.projectName: 'test'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'ocard-server'  # 替換為你的 SonarQube 服務連接名稱
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(sonar.projectKey)'
    cliProjectName: '$(sonar.projectName)'

- script: |
    echo Running SonarQube Scanner
    ./gradlew sonarqube -Dsonar.projectKey=$(sonar.projectKey) -Dsonar.projectName=$(sonar.projectName)
  displayName: 'Run SonarQube Scanner'

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
